# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <remove_redundant>
  "x1",
  # <remove_redundant>
  "x2",
  # <remove_redundant>
  "x3",
  # <remove_redundant>
  "x4",
  # <remove_redundant>
  "x5",
  NULL
))
