# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <group_3>
  "a1",
  # <group_3>
  "a2",
  # <group_3>
  "a3",
  # <group_3>
  "code",
  # <group_3>
  "G",
  # <group_3>
  "i1",
  # <group_3>
  "i2",
  # <group_3>
  "i3",
  # <group_3>
  "N",
  # <remove_redundant>
  # <split_first>
  "x1",
  # <remove_redundant>
  # <split_first>
  "x2",
  # <remove_redundant>
  # <split_first>
  "x3",
  # <remove_redundant>
  # <split_first>
  "x4",
  # <remove_redundant>
  # <split_first>
  "x5",
  NULL
))
